language: java

sudo: required
dist: trusty

before_install:
  - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy main' > /etc/apt/sources.list.d/mono-xamarin.list"
  - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main' >> /etc/apt/sources.list.d/mono-xamarin.list"
  - sudo apt-get -qq update
  - sudo apt-get install --force-yes mono-devel

jdk:
  - openjdk8

script:
  - mvn clean verify

notifications:
  email:
    recipients:
      - rikard@ngs.hr
